force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Épica</label>
    <nameField>
        <label>Nome de Épica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Épicas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <summarizedField>AgileWork__c.RemainingBaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <label># Pontos Restantes Dev</label>
    <summarizedField>AgileWork__c.RemainingDevPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Liberado para Validação</fullName>
            </value>
            <value>
                <fullName>Em Validação</fullName>
            </value>
            <value>
                <fullName>Encerrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Encerrada</fullName>
                <isActive>false</isActive>
                <label>Encerrada</label>
            </value>
            <value>
                <fullName>Não iniciada</fullName>
                <isActive>false</isActive>
                <label>Não iniciada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Épicas</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/AgileProject__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Nome de Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileProject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Data de início do projeto.</description>
    <inlineHelpText>Data de início do projeto.</inlineHelpText>
    <label>Data de início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/ReleasePhase__c.field-meta.xml
<CustomField>
    <fullName>ReleasePhase__c</fullName>
    <inlineHelpText>Este campo indica a fase da Release que esta sendo executada a Sprint.</inlineHelpText>
    <label>Fase da Release</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProjectPhases</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciada</fullName>
                <default>true</default>
                <label>Não Iniciada</label>
            </value>
            <value>
                <fullName>Em Execução</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeam__c/AgileTeam__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <label>Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeam__c/fields/AgileProject__c.field-meta.xml
<CustomField>
    <fullName>AgileProject__c</fullName>
    <label>Projeto</label>
    <referenceTo>AgileProject__c</referenceTo>
    <relationshipLabel>Times</relationshipLabel>
    <relationshipName>Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <label>Épico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileEpic__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/SprintRank__c.field-meta.xml
<CustomField>
    <fullName>SprintRank__c</fullName>
    <defaultValue>2</defaultValue>
    <inlineHelpText>Este campo indica qual será a ordem de execução da Work dentro da Sprint que estiver alocada.</inlineHelpText>
    <label>Ordem na Sprint</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nova</fullName>
                <default>true</default>
                <label>Nova</label>
            </value>
            <value>
                <fullName>Em Levantamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Informações</fullName>
            </value>
            <value>
                <fullName>Em Escrita</fullName>
            </value>
            <value>
                <fullName>Revisão Arquiteto</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Sprint Backlog</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Aguardando APK/IPA</fullName>
            </value>
            <value>
                <fullName>Aguardando Deploy QA</fullName>
            </value>
            <value>
                <fullName>Em Teste Interno</fullName>
            </value>
            <value>
                <fullName>Liberado para PO</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Encerrada</fullName>
            </value>
            <value>
                <fullName>Aguardando APK%2FIPA</fullName>
                <isActive>false</isActive>
                <label>Aguardando APK%2FIPA</label>
            </value>
            <value>
                <fullName>Aguardando Deploy PROD</fullName>
                <isActive>false</isActive>
                <label>Aguardando Deploy PROD</label>
            </value>
            <value>
                <fullName>Em Validação Interna</fullName>
                <isActive>false</isActive>
                <label>Em Validação Interna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Priorities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Baixa</fullName>
        <default>true</default>
        <label>Baixa</label>
    </customValue>
    <customValue>
        <fullName>Média</fullName>
    </customValue>
    <customValue>
        <fullName>Alta</fullName>
    </customValue>
    <customValue>
        <fullName>Muita Alta</fullName>
    </customValue>
    <description>Lista de Prioridades</description>
    <masterLabel>Prioridades</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProjectPhases.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Archt</fullName>
    </customValue>
    <customValue>
        <fullName>Construct</fullName>
    </customValue>
    <customValue>
        <fullName>Homolog</fullName>
    </customValue>
    <customValue>
        <fullName>Go-Live</fullName>
    </customValue>
    <customValue>
        <fullName>Op. Assist</fullName>
    </customValue>
    <customValue>
        <fullName>Mgmt</fullName>
    </customValue>
    <masterLabel>Fase do Projeto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SprintBacklogWorkControllerTest.cls
@isTest
public with sharing class SprintBacklogWorkControllerTest {

    @TestSetup
    static void makeData(){
        // PROJECT
        AgileProject__c project = new AgileProject__c(Name = 'Test Project');
        insert project;

        // TEAM
        List<AgileTeam__c> teamList = new List<AgileTeam__c>();

        AgileTeam__c team1 = new AgileTeam__c();
        team1.Name                      = 'Team 1';
        team1.AgileProject__c          	= project.Id;
        //team1.Account__c                  = account1.Id;

        teamList.add(team1);

        insert teamList;
        
        // SPRINT
        List<AgileSprint__c> sprintList = new List<AgileSprint__c>();

        AgileSprint__c sprint1 = new AgileSprint__c();
        sprint1.Name                = '2020.09 Sprint 1';
        sprint1.StartDate__c        = Date.today();
        sprint1.FinalDate__c          = (Date.today()).addDays(15);
        sprint1.ReleasePhase__c     = 'Construct';
        sprint1.Team__c             = team1.Id;

        sprintList.add(sprint1);
        
        insert sprintList;
        
        // EPIC
        AgileEpic__c epic = new AgileEpic__c(
        	Name = 'Épic Test',
            Priority__c = 'Baixa',
            Team__c = team1.Id
        );
        insert epic;
        
        // WORK
        AgileWork__c SprintBacklogWork = new AgileWork__c();
        SprintBacklogWork.name                  = 'Validade Work';
        SprintBacklogWork.Sprint__c             = sprint1.Id;
        SprintBacklogWork.Status__c             = 'Sprint Backlog';
        SprintBacklogWork.SprintRank__c         = 1;
        SprintBacklogWork.Team__c               = team1.Id;
        SprintBacklogWork.AgileEpic__c          = epic.Id;
        SprintBacklogWork.RemainingBaPoints__c  = 4.0;
        SprintBacklogWork.RemainingDevPoints__c = 4.0;
        
        insert SprintBacklogWork;

    }

    @isTest
    public static void getWorkList() {
        SprintBacklogWorkController SprintBacklog = new SprintBacklogWorkController();
        Test.startTest();
        SprintBacklog.getWorkList('','');
        Test.stopTest();
    }

    @isTest
    public static void getStatusList() {
        SprintBacklogWorkController SprintBacklog = new SprintBacklogWorkController();
        Test.startTest();
        SprintBacklog.getStatusList();
        Test.stopTest();
    }

}