force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Épica</label>
    <nameField>
        <label>Nome de Épica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Épicas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <summarizedField>AgileWork__c.BaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Release</label>
    <referenceTo>AgileRelease__c</referenceTo>
    <relationshipLabel>Épicos</relationshipLabel>
    <relationshipName>epicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <summarizedField>AgileWork__c.RemainingBaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Liberado para Validação</fullName>
            </value>
            <value>
                <fullName>Em Validação</fullName>
            </value>
            <value>
                <fullName>Encerrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Encerrada</fullName>
                <isActive>false</isActive>
                <label>Encerrada</label>
            </value>
            <value>
                <fullName>Não iniciada</fullName>
                <isActive>false</isActive>
                <label>Não iniciada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <referenceTo>AgileRelease__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciada</fullName>
                <default>true</default>
                <label>Não Iniciada</label>
            </value>
            <value>
                <fullName>Em Execução</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/AgileTask__c.object-meta.xml
<CustomObject>
    <label>Tarefa da work</label>
    <nameField>
        <label>Tarefa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarefas da work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTask__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <inlineHelpText>Neste campo devemos fazer a classificação do Bug, após análise. Por padrão todo bug nasce como &apos;Bug&apos;!</inlineHelpText>
    <label>Classificação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bug</fullName>
                <default>true</default>
                <label>Bug</label>
            </value>
            <value>
                <fullName>BugNoGo</fullName>
                <label>Bug No-Go</label>
            </value>
            <value>
                <fullName>Improvement</fullName>
                <label>Melhorias</label>
            </value>
            <value>
                <fullName>WorkAsDesigned</fullName>
                <label>Orientação</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <displayFormat>T{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Codigo</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Esta campo indica em qual Sprint essa tarefa foi concluída</inlineHelpText>
    <label>Sprint Realizada</label>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Devemos indicar qual Work essa tarefa esta executando.</inlineHelpText>
    <label>Work</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>AgileWork__c.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileWork__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tarefas gerais do projeto</description>
    <label>Tarefa</label>
</RecordType>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <label>Épico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileEpic__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Escala Fibonacci 1,	2, 3,	5, 8,	13, 21, 34,55, 89, 144, 233, 377</inlineHelpText>
    <label># Pontos Estimados</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>AgileRelease__c.Team__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileRelease__c</referenceTo>
    <relationshipLabel>Works da Release</relationshipLabel>
    <relationshipName>ReleaseWorks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nova</fullName>
                <default>true</default>
                <label>Nova</label>
            </value>
            <value>
                <fullName>Em Levantamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Informações</fullName>
            </value>
            <value>
                <fullName>Em Escrita</fullName>
            </value>
            <value>
                <fullName>Revisão Arquiteto</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Sprint Backlog</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Aguardando APK/IPA</fullName>
            </value>
            <value>
                <fullName>Aguardando Deploy QA</fullName>
            </value>
            <value>
                <fullName>Em Teste Interno</fullName>
            </value>
            <value>
                <fullName>Liberado para PO</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Encerrada</fullName>
            </value>
            <value>
                <fullName>Aguardando APK%2FIPA</fullName>
                <isActive>false</isActive>
                <label>Aguardando APK%2FIPA</label>
            </value>
            <value>
                <fullName>Aguardando Deploy PROD</fullName>
                <isActive>false</isActive>
                <label>Aguardando Deploy PROD</label>
            </value>
            <value>
                <fullName>Em Validação Interna</fullName>
                <isActive>false</isActive>
                <label>Em Validação Interna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/WorkCode__c.field-meta.xml
<CustomField>
    <fullName>WorkCode__c</fullName>
    <displayFormat>W{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Código da Work</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/SprintBacklogWorkDAO.cls
// public with sharing class WorkDAO implements IWorkDAO {
public with sharing class SprintBacklogWorkDAO implements SprintBacklogIWorkDAO {
    public AgileWork__c castingObject(SObject obj) {
        return (AgileWork__c) obj;
    }


    public Schema.DescribeFieldResult getTaskStatusDescribeFieldResult() {
        return AgileTask__c.Status__c.getDescribe();
    }

    public Schema.DescribeFieldResult getTaskClassificationDescribeFieldResult() {
        return AgileTask__c.Classification__c.getDescribe();
    }

    public Schema.DescribeFieldResult getWorkStatusDescribeFieldResult() {
        return AgileWork__c.Status__c.getDescribe();
    }

    public List<AgileWork__c> getWorkList(String sprintId) {
        return [
            SELECT  Id, Name,WorkCode__c,
                    Status__c, toLabel(Status__c) StatusLabel, Sprint__r.name, AgileEpic__r.Release__r.name, AgileEpic__r.name, BaPoints__c,
                    RemainingBaPoints__c,
                    SprintRank__c,
                    (
                        SELECT  Id, Name, RemainingEffort__c, Work__c, Code__c, EstimatedEffort__c,
                                Status__c, toLabel(Status__c) StatusLabel,
                                RecordTypeId, RecordType.DeveloperName, RecordType.Name,
                                AssignedTo__c, AssignedTo__r.AgileResource__r.AgileUser__r.Name, AssignedTo__r.AgileResource__r.AgileUser__r.FullPhotoUrl
                                , AssignedTo__r.Name
                                , Sprint__c
                                , Classification__c, toLabel(Classification__c) ClassificationLabel
                                , TestedWithBug__c
                            FROM  Tasks__r
                        ORDER BY  Name
                    ) 
                FROM  AgileWork__c
                WHERE  Sprint__c = :sprintId
            ORDER BY  SprintRank__c NULLS LAST, Name
        ];
    }
    public List<AgileWork__c> getWorkList(String sprintId, String teamId) {
        return [
            SELECT  Id, Name,WorkCode__c,
                    Status__c, toLabel(Status__c) StatusLabel, Sprint__r.name, AgileEpic__r.Release__r.name, AgileEpic__r.name, BaPoints__c,
                    RemainingBaPoints__c,
                    SprintRank__c,
                    (
                        SELECT  Id, Name, RemainingEffort__c, Work__c, Code__c, EstimatedEffort__c,
                                Status__c, toLabel(Status__c) StatusLabel,
                                RecordTypeId, RecordType.DeveloperName, RecordType.Name,
                                AssignedTo__c, AssignedTo__r.AgileResource__r.AgileUser__r.Name, AssignedTo__r.AgileResource__r.AgileUser__r.FullPhotoUrl
                                , AssignedTo__r.Name
                                , Sprint__c
                                , Classification__c, toLabel(Classification__c) ClassificationLabel
                                , TestedWithBug__c
                            FROM  Tasks__r
                        ORDER BY  Name
                    ) 
                FROM  AgileWork__c
                WHERE  Sprint__c = :sprintId OR (Sprint__c = null AND Team__c = :teamId)
            ORDER BY  SprintRank__c NULLS LAST, Name
        ];
    }

    public Map<String, AgileWork__c> getWorkByIdsList(List<String> workIds) {
        return new Map<String, AgileWork__c>([
            SELECT  Id, Name,WorkCode__c,
                    Status__c, toLabel(Status__c) StatusLabel, Sprint__r.name, AgileEpic__r.Release__r.name, AgileEpic__r.name, BaPoints__c,
                    RemainingBaPoints__c,
                    SprintRank__c,
                    (
                        SELECT  Id, Name, RemainingEffort__c, Work__c, Code__c, EstimatedEffort__c,
                                Status__c, toLabel(Status__c) StatusLabel,
                                RecordTypeId, RecordType.DeveloperName, RecordType.Name,
                                AssignedTo__c, AssignedTo__r.AgileResource__r.AgileUser__r.Name, AssignedTo__r.AgileResource__r.AgileUser__r.FullPhotoUrl
                                , AssignedTo__r.Name
                                , Sprint__c
                                , Classification__c, toLabel(Classification__c) ClassificationLabel
                                , TestedWithBug__c
                            FROM  Tasks__r
                        ORDER BY  Name
                    ) 
                FROM  AgileWork__c
                WHERE  Id IN :workIds
            ORDER BY  SprintRank__c NULLS LAST, Name
        ]);
    }

    public RemotingResult setSprint(SprintBacklogWorkController.SprintData request) {
        RemotingResult response;
        Savepoint sp = Database.setSavepoint();
        try {
            response = new RemotingResult();

            Set<Id> wkIdSet = new Set<Id>();
            for(SprintBacklogWorkController.WorkData wk : request.workSprintList){
                wkIdSet.add(wk.id);
            }            
            for(SprintBacklogWorkController.WorkData wk : request.workBacklogList){
                wkIdSet.add(wk.id);
            }
			System.debug('wkIdSet ' + wkIdSet);
            Map<Id, AgileWork__c> SprintBacklogMap = new Map<Id, AgileWork__c>([SELECT id, BaPoints__c FROM AgileWork__c WHERE Id IN : wkIdSet]);
            
            integer position = 0;
            List<AgileWork__c> wkList = new List<AgileWork__c>();
            for(SprintBacklogWorkController.WorkData wk : request.workSprintList){
                Decimal storys = SprintBacklogMap.get(wk.id).BaPoints__c != null ? SprintBacklogMap.get(wk.id).BaPoints__c : 0;
				System.debug('request.id ' + request.id);
                wkList.add(new AgileWork__c(Id = wk.id, Sprint__c = request.id, BaPoints__c = storys, SprintRank__c = position));
                position++;
            }
            
            position = 0;
            for(SprintBacklogWorkController.WorkData wk : request.workBacklogList){
                Decimal storys = SprintBacklogMap.get(wk.id).BaPoints__c != null ? SprintBacklogMap.get(wk.id).BaPoints__c : 0;
                wkList.add(new AgileWork__c(Id = wk.id, Sprint__c = null, BaPoints__c = storys, SprintRank__c = position));
                position++;
            }
			
            update wkList;
            response.setMessage(request.id);
        } catch (Exception e) {
            Database.rollback(sp);
            response = new RemotingResult(e);
        }
        return response;
    }

    public RemotingResult setWork(SprintBacklogWorkController.WorkData request) {
        RemotingResult response;
        Savepoint sp = Database.setSavepoint();
        try {
            response = new RemotingResult();
            AgileWork__c work = [
                SELECT  Id
                    FROM  AgileWork__c 
                    WHERE  Id = :request.id
            FOR UPDATE
            ];
            work.Status__c    = request.status.key;
            work.RemainingBaPoints__c  = request.remainingPoint;
            update work;
            response.setMessage(work.Id);
        } catch (Exception e) {
            Database.rollback(sp);
            response = new RemotingResult(e);
        }
        return response;
    }

    public RemotingResult setTask(SprintBacklogWorkController.TaskData request) {
        RemotingResult response;
        Savepoint sp = Database.setSavepoint();
        try {
            response = new RemotingResult();
            AgileTask__c task = [
                SELECT  Id, Name, Description__c, 
                    EstimatedEffort__c, RemainingEffort__c, Work__c 
                    FROM  AgileTask__c 
                    WHERE  Id = :request.id 
            FOR UPDATE
            ];
            task.Status__c             = request.status.key;
            task.Classification__c     = request.classification != null ? request.classification.key : null;
            task.RemainingEffort__c    = request.remainingHours;
            task.TestedWithBug__c      = request.testedWithBug;
            task.EstimatedEffort__c    = request.initialHours;
            task.AssignedTo__c         = request.assignedTo != null ? request.assignedTo.id : null;

            if(String.isBlank(request.workId)) {
                request.workId = task.Work__c;
            }

            //agf_ADM_TaskTriggerHandler.run = false;
            if(task.Work__c == request.workId) {
                update task;
                response.setMessage(task.Id);
            }else {
                AgileTask__c taskNew    = task.clone(false);
                taskNew.Work__c        = request.workId;
                insert taskNew;
                delete task;
                response.setMessage(taskNew.Id);
            }
            //agf_ADM_TaskTriggerHandler.run = true;

        } catch (Exception e) {
            Database.rollback(sp);
            response = new RemotingResult(e);
        }
        return response;
    }
}