force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Épica</label>
    <nameField>
        <label>Nome de Épica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Épicas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Prioridade</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Liberado para Validação</fullName>
            </value>
            <value>
                <fullName>Em Validação</fullName>
            </value>
            <value>
                <fullName>Encerrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Encerrada</fullName>
                <isActive>false</isActive>
                <label>Encerrada</label>
            </value>
            <value>
                <fullName>Não iniciada</fullName>
                <isActive>false</isActive>
                <label>Não iniciada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Épicas</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/AgileProject__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Nome de Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileProject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Data de início do projeto.</description>
    <inlineHelpText>Data de início do projeto.</inlineHelpText>
    <label>Data de início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileResource__c/AgileResource__c.object-meta.xml
<CustomObject>
    <label>Recurso</label>
    <nameField>
        <label>Nome de Recurso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileResource__c/fields/AgileUser__c.field-meta.xml
<CustomField>
    <fullName>AgileUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recursos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/ReleasePhase__c.field-meta.xml
<CustomField>
    <fullName>ReleasePhase__c</fullName>
    <inlineHelpText>Este campo indica a fase da Release que esta sendo executada a Sprint.</inlineHelpText>
    <label>Fase da Release</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProjectPhases</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciada</fullName>
                <default>true</default>
                <label>Não Iniciada</label>
            </value>
            <value>
                <fullName>Em Execução</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/AgileTask__c.object-meta.xml
<CustomObject>
    <label>Tarefa da work</label>
    <nameField>
        <label>Tarefa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarefas da work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTask__c/fields/EstimatedEffort__c.field-meta.xml
<CustomField>
    <fullName>EstimatedEffort__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Neste campo devemos adicionar as horas estimadas para esta tarefa</inlineHelpText>
    <label>Esforço Estimado (hr)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Esta campo indica em qual Sprint essa tarefa foi concluída</inlineHelpText>
    <label>Sprint Realizada</label>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Taks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Devemos indicar qual Work essa tarefa esta executando.</inlineHelpText>
    <label>Work</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>AgileWork__c.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileWork__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/recordTypes/Bug.recordType-meta.xml
<RecordType>
    <fullName>Bug</fullName>
    <active>true</active>
    <description>Erros encontrados nas Sprints durante período de Homologação</description>
    <label>Ocorrência</label>
</RecordType>

force-app/main/default/objects/AgileTask__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tarefas gerais do projeto</description>
    <label>Tarefa</label>
</RecordType>

force-app/main/default/objects/AgileTask__c/recordTypes/Test.recordType-meta.xml
<RecordType>
    <fullName>Test</fullName>
    <active>true</active>
    <description>Testes realizados na Sprint ou durante a homologação</description>
    <label>Teste</label>
</RecordType>

force-app/main/default/objects/AgileTeam__c/AgileTeam__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <label>Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeam__c/fields/AgileProject__c.field-meta.xml
<CustomField>
    <fullName>AgileProject__c</fullName>
    <label>Projeto</label>
    <referenceTo>AgileProject__c</referenceTo>
    <relationshipLabel>Times</relationshipLabel>
    <relationshipName>Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/AgileTeamMember__c.object-meta.xml
<CustomObject>
    <label>Membro do Time</label>
    <nameField>
        <label>Nome de Membro do Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros do Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileResource__c.field-meta.xml
<CustomField>
    <fullName>AgileResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso</label>
    <referenceTo>AgileResource__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileTeam__c.field-meta.xml
<CustomField>
    <fullName>AgileTeam__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Alocação</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Função</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FunctionAgile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <label>Épico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileEpic__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/recordTypes/CaseBug.recordType-meta.xml
<RecordType>
    <fullName>CaseBug</fullName>
    <active>true</active>
    <description>Utilize para registrar um impedimento ou possível problema a ser investigado.</description>
    <label>Chamado</label>
</RecordType>

force-app/main/default/globalValueSets/FunctionAgile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>InternalManager</fullName>
        <label>Gestor da Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalProjectManager</fullName>
        <label>Gerente de Projeto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalArchitect</fullName>
        <label>Arquiteto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalConsultant</fullName>
        <label>Consultor Funcional</label>
    </customValue>
    <customValue>
        <fullName>InternalDeveloper</fullName>
        <label>Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerManager</fullName>
        <label>Cliente: Gestor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProjectManager</fullName>
        <label>Cliente: Gerente de Projeto</label>
    </customValue>
    <customValue>
        <fullName>CustomerDeveloper</fullName>
        <label>Cliente: Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProductOwner</fullName>
        <label>Cliente: Product Owner</label>
    </customValue>
    <customValue>
        <fullName>CustomerIT</fullName>
        <label>Cliente: Usuário da TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerITLegacyTeam</fullName>
        <label>Cliente: Time Legado TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerKeyUser</fullName>
        <label>Cliente: Usuário Chave</label>
    </customValue>
    <masterLabel>Função Time Agile</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Priorities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Baixa</fullName>
        <default>true</default>
        <label>Baixa</label>
    </customValue>
    <customValue>
        <fullName>Média</fullName>
    </customValue>
    <customValue>
        <fullName>Alta</fullName>
    </customValue>
    <customValue>
        <fullName>Muita Alta</fullName>
    </customValue>
    <description>Lista de Prioridades</description>
    <masterLabel>Prioridades</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProjectPhases.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Archt</fullName>
    </customValue>
    <customValue>
        <fullName>Construct</fullName>
    </customValue>
    <customValue>
        <fullName>Homolog</fullName>
    </customValue>
    <customValue>
        <fullName>Go-Live</fullName>
    </customValue>
    <customValue>
        <fullName>Op. Assist</fullName>
    </customValue>
    <customValue>
        <fullName>Mgmt</fullName>
    </customValue>
    <masterLabel>Fase do Projeto</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SprintBacklogProjectControllerTest.cls
/**
 * @description       : 
 * @descrição         : 
 * @author            : Lucas Meneguelli
 * @group             : 
 * @last modified on  : 10-01-2025
 * @last modified by  : Luíz Suliman
**/
@isTest
public with sharing class SprintBacklogProjectControllerTest {
    @TestSetup
    static void setupData() {
        SprintBacklogSprintHandler.run = false;

        // ACCOUNT
        List<Account> accountList = new List<Account>();

        Account account1 = new Account();
        account1.Name                   = 'account 1';
        //account1.Unidade_de_Negocio__c  = 'Nèscara';

        accountList.add(account1);

        insert accountList;

        Contact cont1 = new Contact();
        cont1.LastName = 'Cont 1';
        cont1.AccountId = account1.Id;
        cont1.Email = 'demo@taak.com.test';
        Insert cont1;
        
        // PROJECT
        AgileProject__c project = new AgileProject__c(Name = 'Test Project');
        insert project;

        // TEAM
        List<AgileTeam__c> teamList = new List<AgileTeam__c>();

        AgileTeam__c team1 = new AgileTeam__c();
        team1.Name                      = 'Team 1';
        team1.AgileProject__c          	= project.Id;
        //team1.Account__c                  = account1.Id;

        teamList.add(team1);

        insert teamList;

        // TEAM MEMBER
        List<AgileTeamMember__c> teamMemberList = new List<AgileTeamMember__c>();

        AgileResource__c resources = new AgileResource__c(AgileUser__c = UserInfo.getUserId());

        AgileTeamMember__c teamMember1 = new AgileTeamMember__c();
        teamMember1.Allocated__c  = 100;
        teamMember1.AgileResource__c             = resources.Id;
        teamMember1.AgileTeam__c             = team1.Id;
        teamMember1.Role__c             = 'InternalConsultant';
        teamMember1.StartDate__c           = Date.today();
        teamMember1.FinalDate__c             = Date.today().addDays(30);

        teamMemberList.add(teamMember1);

        insert teamMemberList;

        // SPRINT
        List<AgileSprint__c> sprintList = new List<AgileSprint__c>();

        AgileSprint__c sprint1 = new AgileSprint__c();
        sprint1.Name                = '2020.09 Sprint 1';
        sprint1.StartDate__c        = Date.today();
        sprint1.FinalDate__c          = (Date.today()).addDays(15);
        sprint1.ReleasePhase__c     = 'Construct';
        sprint1.Team__c             = team1.Id;

        sprintList.add(sprint1);

        insert sprintList;

        
        // // Burndown
        // List<AgileBurndown__c> burndownList = new List<AgileBurndown__c>();
        // AgileBurndown__c burndown1 = new AgileBurndown__c();
        // burndown1.Sprint__c             = Sprint1.Id;
        // burndown1.Type__c               = 'Baseline';
        // burndown1.EstimatedEffort__c    = 4;
        // burndown1.Date__c               = Date.today();

        // burndownList.add(burndown1);

        // AgileBurndown__c burndown2 = new AgileBurndown__c();
        // burndown2.Sprint__c             = Sprint1.Id;
        // burndown2.Type__c               = 'Actual';
        // burndown2.EstimatedEffort__c    = 3;
        // burndown2.Date__c               = Date.today();

        // burndownList.add(burndown2);

        // insert burndownList;

        // EPIC
        AgileEpic__c epic = new AgileEpic__c(
        	Name = 'Épic Test',
            Priority__c = 'Baixa',
            Team__c = team1.Id
        );
        insert epic;
        
        // WORK
        System.debug(team1);
        List<AgileWork__c> workList = new List<AgileWork__c>();

        AgileWork__c work1 = new AgileWork__c();
        work1.Name              = 'Work 1 Subject';
        work1.Sprint__c         = sprint1.Id;
        work1.Status__c   = 'Sprint Backlog';
        work1.SprintRank__c     = 1;
        //work1.Account__c        = account1.Id;
        work1.Team__c           = team1.Id;
        work1.AgileEpic__c      = epic.Id;
        work1.RemainingBaPoints__c = 4.0;
        work1.RemainingDevPoints__c = 4.0;

        workList.add(work1);

        AgileWork__c work2 = new AgileWork__c();
        work2.Name              = 'Work 2 Subject';
        work2.Sprint__c         = sprint1.Id;
        work2.Status__c   = 'Sprint Backlog';
        work2.SprintRank__c     = 2;
        //work2.Account__c        = account1.Id;
        work2.Team__c           = team1.Id;
        work2.AgileEpic__c      = epic.Id;
        work2.RemainingBaPoints__c = 4.0;
        work2.RemainingDevPoints__c = 4.0;
        
        workList.add(work2);

        insert workList;

        // TASK
        List<AgileTask__c> taskList = new List<AgileTask__c>();

        AgileTask__c task1 = new AgileTask__c();
        task1.Name              = 'Task 1 Subject';
        task1.EstimatedEffort__c  = 8;
        task1.RemainingEffort__c  = 8;
        task1.Work__c           = work1.Id;
        task1.Team__c           = team1.Id;
        task1.AssignedTo__c     = teamMember1.Id;
        task1.Classification__c = 'Bug';

        taskList.add(task1);

        insert taskList;
        
        SprintBacklogSprintHandler.run = true;
    }

    @isTest
    public static void SprintBacklogController() {
        ApexPages.StandardController sc = new ApexPages.standardController(new Account());
        Test.startTest();

        SprintBacklogController controller = new SprintBacklogController(sc);
        controller = new SprintBacklogController();
        new SprintBacklogUserController.UserResult(new SprintBacklogController.SprintBacklogControllerException());
        PicklistData pickList = new PicklistData();
        PicklistData pickList2 = new PicklistData('teste','teste');
        PicklistData pickList3 = new PicklistData('teste','teste','teste');
        RemotingResult result = new RemotingResult();
        result = new RemotingResult(true);
        result = new RemotingResult(true, 'message');
        result = new RemotingResult(true, 'code', 'message');
        result = new RemotingResult(true, 'code', 'message', 'description');
        result = new RemotingResult(new SprintBacklogController.SprintBacklogControllerException());
        result = new RemotingResult(new SprintBacklogController.SprintBacklogControllerException(), 'message');

        SprintBacklogWorkDAO workC = new SprintBacklogWorkDAO();
        workC.getTaskClassificationDescribeFieldResult();

        Test.stopTest();
    }

    @isTest
    public static void getBurndown() {
        Test.startTest();

        AgileSprint__c sprint1 = [SELECT Id FROM AgileSprint__c LIMIT 1];
        SprintBacklogBurndownController.BurndownResult result = SprintBacklogController.getBurndown(sprint1.Id);
        System.debug(JSON.serializePretty(result));
        System.assertEquals(false, result.hasError);

        SprintBacklogBurndownController.BurndownResult resultBurndown = new SprintBacklogBurndownController.BurndownResult(new SprintBacklogController.SprintBacklogControllerException());

        Test.stopTest();
    }
   
    @isTest
    public static void getTeamList() {
        Test.startTest();

        SprintBacklogTeamsController.TeamResult result = SprintBacklogController.getTeamList();
        System.debug(JSON.serializePretty(result));
        System.assertEquals(false, result.hasError);

        new SprintBacklogTeamsController.TeamResult(new SprintBacklogController.SprintBacklogControllerException());
        new SprintBacklogTeamsController.TeamData();
        new SprintBacklogTeamsController.MemberData();
        new SprintBacklogTeamsController.SprintData();

        Test.stopTest();
    }

    @isTest
    public static void getWorkList() {
        AgileSprint__c sprint1 = [SELECT Id, Team__c FROM AgileSprint__c LIMIT 1];

        Test.startTest();

        SprintBacklogWorkController.WorkResult result = SprintBacklogController.getWorkList(new List<String>{sprint1.id,sprint1.team__c });
        System.debug(JSON.serializePretty(result));
        System.assertEquals(false, result.hasError);

        SprintBacklogController.setSprint(null);
        new SprintBacklogWorkDAO().getWorkByIdsList(new List<String>());
        new SprintBacklogWorkDAO().getWorkList(sprint1.id);
        
        SprintBacklogWorkController.SprintData request = new SprintBacklogWorkController.SprintData();
        request.workSprintList  = new List<SprintBacklogWorkController.WorkData>();
        request.workBacklogList = new List<SprintBacklogWorkController.WorkData>();
        request.id              = sprint1.id;

        new SprintBacklogWorkDAO().setSprint(request);

        new SprintBacklogWorkController.StatusResult(new SprintBacklogController.SprintBacklogControllerException());
        new SprintBacklogWorkController.WorkResult(new SprintBacklogController.SprintBacklogControllerException());
        new SprintBacklogWorkController.AssignedToData();

        Test.stopTest();
    }

    @isTest
    public static void setWork() {
        SprintBacklogWorkController.WorkData request = new SprintBacklogWorkController.WorkData();
        AgileWork__c work1 = [SELECT Id, Status__c, RemainingBaPoints__c FROM AgileWork__c WHERE Name = 'Work 2 Subject' LIMIT 1];
        request.id = work1.Id;
        request.status = new PicklistData(work1.Status__c, work1.Status__c);
        request.remainingPoint = work1.RemainingBaPoints__c;

        Test.startTest();

        RemotingResult result = SprintBacklogController.setWork(request);
        System.debug(JSON.serializePretty(result));
        System.assertEquals(false, result.hasError);

        Test.stopTest();
    }

    @isTest
    public static void setTask() {
        SprintBacklogWorkController.AssignedToData assignedData = new SprintBacklogWorkController.AssignedToData([SELECT Id, Name, Role__c ,AgileResource__r.AgileUser__r.Name , AgileResource__r.AgileUser__r.FullPhotoUrl FROM AgileTeamMember__c Limit 1]);
        SprintBacklogWorkController.TaskData request = new SprintBacklogWorkController.TaskData();
        AgileWork__c work2  = [SELECT Id, Status__c FROM AgileWork__c WHERE Name = 'Work 2 Subject' LIMIT 1];
        AgileTask__c task1  = [SELECT Id, Status__c, Classification__c, Work__c FROM AgileTask__c LIMIT 1];
        request.id              = task1.Id;
        request.status          = new PicklistData(task1.Status__c, task1.Status__c);
        request.classification  = new PicklistData(task1.Classification__c, task1.Classification__c);
        request.remainingHours  = 2;
        request.assignedTo      = assignedData;

        Test.startTest();
        
        RemotingResult result = SprintBacklogController.setTask(request);
        System.debug(JSON.serializePretty(result));
        //System.assertEquals(false, result.hasError);
        
        request.workId = work2.Id;
        result = SprintBacklogController.setTask(request);
        System.debug(JSON.serializePretty(result));
        //System.assertEquals(false, result.hasError);

        Test.stopTest();
    }

    @isTest
    public static void setMailTask() {
        SprintBacklogWorkController.AssignedToData assignedData = new SprintBacklogWorkController.AssignedToData([SELECT Id, Name, Role__c ,AgileResource__r.AgileUser__r.Name , AgileResource__r.AgileUser__r.FullPhotoUrl FROM AgileTeamMember__c Limit 1]);
        SprintBacklogWorkController.TaskData request = new SprintBacklogWorkController.TaskData();
        // List<Contact> ContractNesc = [SELECT Id, AccountId FROM Contact WHERE Account.Name like '%account 1%' limit 1];
        AgileTeam__c team1  = [SELECT Id FROM AgileTeam__c WHERE Name = 'Team 1' LIMIT 1];
        AgileWork__c work2  = [SELECT Id, Status__c, Sprint__c FROM AgileWork__c WHERE Name = 'Work 2 Subject' LIMIT 1];
        AgileTask__c task1  = [SELECT Id, Status__c, Classification__c, Work__c, work__r.Sprint__c FROM AgileTask__c LIMIT 1];
        request.id              = task1.Id;
        request.status          = new PicklistData(task1.Status__c, task1.Status__c);
        request.classification  = new PicklistData(task1.Classification__c, task1.Classification__c);
        request.remainingHours  = 2;
        request.assignedTo      = assignedData;

        Test.startTest();

        // team1.Contact__c = ContractNesc[0].Id;
        // team1.GeneralEmailAddress__c = 'demo@taak.com.test';
        // team1.TeamEmailAddress__c = 'demo@taak.com.test';
        update team1;

        task1.Status__c = 'In Progress';
        update task1;

        task1.Status__c = 'Completed';
        update task1;

        Delete task1;
        
        // EPIC
        AgileEpic__c epic = new AgileEpic__c(
        	Name = 'Épic Test',
            Priority__c = 'Baixa',
            Team__c = team1.Id
        );
        
        insert epic;

        // List<RecordType> rTP = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType='AgileWork__c' AND DeveloperName = 'CaseBug'];

        List<AgileWork__c> workList = new List<AgileWork__c>();

        AgileWork__c work1 = new AgileWork__c();
        work1.Name              = 'Work 2 CaseBug';
        work1.Sprint__c         = work2.Sprint__c;
        work1.Status__c   = work2.Status__c;
        work1.SprintRank__c     = 1;
        //work1.Account__c        = ContractNesc[0].AccountId;
        work1.Team__c           = team1.Id;
        // work1.RecordTypeId      = rTP[0].Id;
        work1.AgileEpic__c      = epic.Id;

        workList.add(work1);
        Insert workList;


        Test.stopTest();
    }


}