force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Épica</label>
    <nameField>
        <label>Nome de Épica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Épicas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <summarizedField>AgileWork__c.BaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Release</label>
    <referenceTo>AgileRelease__c</referenceTo>
    <relationshipLabel>Épicos</relationshipLabel>
    <relationshipName>epicos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <summarizedField>AgileWork__c.RemainingBaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Liberado para Validação</fullName>
            </value>
            <value>
                <fullName>Em Validação</fullName>
            </value>
            <value>
                <fullName>Encerrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Encerrada</fullName>
                <isActive>false</isActive>
                <label>Encerrada</label>
            </value>
            <value>
                <fullName>Não iniciada</fullName>
                <isActive>false</isActive>
                <label>Não iniciada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/AgileTask__c.object-meta.xml
<CustomObject>
    <label>Tarefa da work</label>
    <nameField>
        <label>Tarefa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarefas da work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTask__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <displayFormat>T{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Codigo</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/EstimatedEffort__c.field-meta.xml
<CustomField>
    <fullName>EstimatedEffort__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Neste campo devemos adicionar as horas estimadas para esta tarefa</inlineHelpText>
    <label>Esforço Estimado (hr)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/RemainingEffort__c.field-meta.xml
<CustomField>
    <fullName>RemainingEffort__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Este campo representas horas que faltam para a tarefa ser completada.</inlineHelpText>
    <label>Esforço Restantes (hr)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Esta campo indica em qual Sprint essa tarefa foi concluída</inlineHelpText>
    <label>Sprint Realizada</label>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/TestedWithBug__c.field-meta.xml
<CustomField>
    <fullName>TestedWithBug__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Este campo indica que foi encontrado um erro no cenário de teste realizado. Quando esse campo é marcado o erro/bug será criado automaticamente na Work que controla os Erros no Backlog da Sprint.</inlineHelpText>
    <label>Testado com erro</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/fields/Work__c.field-meta.xml
<CustomField>
    <fullName>Work__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Devemos indicar qual Work essa tarefa esta executando.</inlineHelpText>
    <label>Work</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>AgileWork__c.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileWork__c</referenceTo>
    <relationshipLabel>Tarefas</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTask__c/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <description>Tarefas gerais do projeto</description>
    <label>Tarefa</label>
</RecordType>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <label>Épico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileEpic__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Escala Fibonacci 1,	2, 3,	5, 8,	13, 21, 34,55, 89, 144, 233, 377</inlineHelpText>
    <label># Pontos Estimados</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Team__c</field>
            <operation>equals</operation>
            <valueField>AgileRelease__c.Team__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileRelease__c</referenceTo>
    <relationshipLabel>Works da Release</relationshipLabel>
    <relationshipName>ReleaseWorks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/SprintRank__c.field-meta.xml
<CustomField>
    <fullName>SprintRank__c</fullName>
    <defaultValue>2</defaultValue>
    <inlineHelpText>Este campo indica qual será a ordem de execução da Work dentro da Sprint que estiver alocada.</inlineHelpText>
    <label>Ordem na Sprint</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nova</fullName>
                <default>true</default>
                <label>Nova</label>
            </value>
            <value>
                <fullName>Em Levantamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Informações</fullName>
            </value>
            <value>
                <fullName>Em Escrita</fullName>
            </value>
            <value>
                <fullName>Revisão Arquiteto</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Sprint Backlog</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Aguardando APK/IPA</fullName>
            </value>
            <value>
                <fullName>Aguardando Deploy QA</fullName>
            </value>
            <value>
                <fullName>Em Teste Interno</fullName>
            </value>
            <value>
                <fullName>Liberado para PO</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Encerrada</fullName>
            </value>
            <value>
                <fullName>Aguardando APK%2FIPA</fullName>
                <isActive>false</isActive>
                <label>Aguardando APK%2FIPA</label>
            </value>
            <value>
                <fullName>Aguardando Deploy PROD</fullName>
                <isActive>false</isActive>
                <label>Aguardando Deploy PROD</label>
            </value>
            <value>
                <fullName>Em Validação Interna</fullName>
                <isActive>false</isActive>
                <label>Em Validação Interna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/WorkCode__c.field-meta.xml
<CustomField>
    <fullName>WorkCode__c</fullName>
    <displayFormat>W{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Código da Work</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/SprintBacklogWorkController.cls
public with sharing class SprintBacklogWorkController {
    private SprintBacklogWorkDAO workDAO             = new SprintBacklogWorkDAO();

    public RemotingResult setWork(WorkData request) {
        return workDAO.setWork(request);
    }

    public RemotingResult setTask(TaskData request) {
        return workDAO.setTask(request);
    }

    public RemotingResult setSprint(SprintData request) {
        System.debug('Requet linha 13 ' + request);
        return workDAO.setSprint(request);
    }


    public WorkResult getWorkList(String sprintId, string teamId) {
        WorkResult response;
        try {
            response = new WorkResult();
            for(SObject work : workDAO.getWorkList(sprintId, teamId)) {
                WorkData wkData = new WorkData(workDAO.castingObject(work));
                if(wkData.hasSprint)
                    response.data.add(wkData);
                else
                    response.dataWithoutSprint.add(wkData);
            }
        } catch (Exception e) {
            response = new WorkResult(e);
        }
        return response;
    }

    public StatusResult getStatusList() {
        StatusResult response;
        try {
            response = new StatusResult();
            Schema.DescribeFieldResult fieldResult = workDAO.getTaskStatusDescribeFieldResult();
            List<Schema.PicklistEntry> picklistEntryList = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry entry : picklistEntryList) {
                response.task.add(new PicklistData(entry.getValue(), entry.getLabel()));
            }

            fieldResult = workDAO.getTaskClassificationDescribeFieldResult();
            picklistEntryList = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry entry : picklistEntryList) {
                response.classification.add(new PicklistData(entry.getValue(), entry.getLabel()));
            }

            fieldResult = workDAO.getWorkStatusDescribeFieldResult();
            picklistEntryList = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry entry : picklistEntryList) {
                response.work.add(new PicklistData(entry.getValue(), entry.getLabel()));
            }
            response.taskCompletedStatus = 'Completed';
        } catch (Exception e) {
            response = new StatusResult(e);
        }
        return response;
    }

    public class StatusResult extends RemotingResult {
        public List<PicklistData> task              = new List<PicklistData>();
        public List<PicklistData> classification    = new List<PicklistData>();
        public List<PicklistData> work              = new List<PicklistData>();
        public String taskCompletedStatus;
        
        public StatusResult() {
            super();
        }

        public StatusResult(Exception e) {
            super(e);
        }
    }

    public class WorkResult extends RemotingResult {
        public List<WorkData> data = new List<WorkData>();
        public List<WorkData> dataWithoutSprint = new List<WorkData>();

        public WorkResult() {
            super();
        }

        public WorkResult(Exception e) {
            super(e);
        }
    }

    public class WorkData {
        public String id;
        public String name;
        public String subject;
        public String epicName;
        public String releaseName;
        public Decimal storyPoints;
        public Decimal estimatedHours;
        public Decimal taskLength;
        public Decimal completedHours;
        public Decimal remainingPoint;
        public Decimal sprintRank;
        public PicklistData status;
        public PicklistData type;

        public Boolean hasEpic;
        public Boolean hasRelease;
        public Boolean hasSprint;

        public Boolean finishedSprint;

        public List<TaskData> taskList = new List<TaskData>();

        public WorkData() {}

        public WorkData(AgileWork__c work) {
            this.id             = work.Id;
            this.name           = work.WorkCode__c;
            this.subject        = work.Name;
            this.completedHours = work.BaPoints__c - work.RemainingBaPoints__c;
            this.remainingPoint = work.RemainingBaPoints__c;
            this.epicName       = work.AgileEpic__r.name;
            this.releaseName    = work.AgileEpic__r.Release__r.name;
            this.hasEpic        = work.AgileEpic__c != null;
            this.hasRelease     = work.AgileEpic__r.Release__c != null;
            this.hasSprint      = work.Sprint__c != null;
            this.finishedSprint = work.BaPoints__c - work.RemainingBaPoints__c <= 0;
            this.storyPoints    = work.BaPoints__c == null ? 0 : work.BaPoints__c;
            this.type           = new PicklistData('Historia', 'Historia');//new PicklistData(work.RecordType.DeveloperName, work.RecordType.Name);
            this.status         = new PicklistData(work.Status__c, (String) work.get('StatusLabel'));
            this.estimatedHours = 0;
            this.sprintRank     = work.SprintRank__c;
            this.taskLength     = 0;
            for(AgileTask__c task : work.Tasks__r) {
                this.taskList.add(new TaskData(task));
                this.estimatedHours += (task.EstimatedEffort__c == null ? 0 : task.EstimatedEffort__c);
                this.taskLength++;
            }
        }
    }

    public class TaskData {
        public String id;
        public String name;
        public String subject;
        public String sprint;
        public Decimal remainingHours;
        public Decimal initialHours;
        public PicklistData type;
        public PicklistData status;
        public PicklistData classification;
        public Boolean testedWithBug;
        public String workId;
        public AssignedToData assignedTo;

        public TaskData() {}

        public TaskData(AgileTask__c task) {
            this.id             = task.Id;
            this.workId         = task.Work__c;
            this.name           = task.Code__c;
            this.subject        = task.Name;
            this.sprint         = task.Sprint__c;
            this.initialHours   = task.EstimatedEffort__c;
            this.remainingHours = task.RemainingEffort__c;
            this.testedWithBug  = task.TestedWithBug__c;
            this.type           = new PicklistData(String.isNotBlank(task.RecordType.DeveloperName) ? task.RecordType.DeveloperName : 'Task', String.isNotBlank(task.RecordType.Name) ? task.RecordType.Name : 'Task');
            this.status         = new PicklistData(task.Status__c, (String) task.get('StatusLabel'));
            this.classification = new PicklistData(task.Classification__c, (String) task.get('ClassificationLabel'));
            this.assignedTo     = new AssignedToData(task.AssignedTo__r);
        }
    }

    public class AssignedToData {
        public String id;
        public String name;
        public String photo;

        public AssignedToData() {}

        public AssignedToData(AgileTeamMember__c member) {
            if(member != null) {
                this.id     = member.Id;
                this.name   = String.isNotBlank(member.Name) ? member.Name : member.AgileResource__r.AgileUser__r.Name;
                this.photo  = member.AgileResource__r.AgileUser__r.FullPhotoUrl;
            }
        }
    }

    public class SprintData {
        public String id;
        public List<WorkData> workSprintList    = new List<WorkData>();
        public List<WorkData> workBacklogList   = new List<WorkData>();
    }

}