force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Épica</label>
    <nameField>
        <label>Nome de Épica</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Épicas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <summarizedField>AgileWork__c.BaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/DevPoints__c.field-meta.xml
<CustomField>
    <fullName>DevPoints__c</fullName>
    <label># Pontos Dev</label>
    <summarizedField>AgileWork__c.DevPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <summarizedField>AgileWork__c.RemainingBaPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <label># Pontos Restantes Dev</label>
    <summarizedField>AgileWork__c.RemainingDevPoints__c</summarizedField>
    <summaryForeignKey>AgileWork__c.AgileEpic__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciado</fullName>
                <default>true</default>
                <label>Não iniciado</label>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Liberado para Validação</fullName>
            </value>
            <value>
                <fullName>Em Validação</fullName>
            </value>
            <value>
                <fullName>Encerrado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Encerrada</fullName>
                <isActive>false</isActive>
                <label>Encerrada</label>
            </value>
            <value>
                <fullName>Não iniciada</fullName>
                <isActive>false</isActive>
                <label>Não iniciada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Épicas</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/AgileProject__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Nome de Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileProject__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projetos</relationshipLabel>
    <relationshipName>Projetos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/GoLiveDate__c.field-meta.xml
<CustomField>
    <fullName>GoLiveDate__c</fullName>
    <label>Data do go-live</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/InitialProjectValue__c.field-meta.xml
<CustomField>
    <fullName>InitialProjectValue__c</fullName>
    <description>Valor acordado do projeto.</description>
    <inlineHelpText>Valor acordado do projeto.</inlineHelpText>
    <label>Valor inicial do projeto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgileProject__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Data de início do projeto.</description>
    <inlineHelpText>Data de início do projeto.</inlineHelpText>
    <label>Data de início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/DevPoints__c.field-meta.xml
<CustomField>
    <fullName>DevPoints__c</fullName>
    <label># Pontos Dev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Iniciada</fullName>
                <default>true</default>
                <label>Não Iniciada</label>
            </value>
            <value>
                <fullName>Em Execução</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeam__c/AgileTeam__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <label>Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeam__c/fields/AgileProject__c.field-meta.xml
<CustomField>
    <fullName>AgileProject__c</fullName>
    <label>Projeto</label>
    <referenceTo>AgileProject__c</referenceTo>
    <relationshipLabel>Times</relationshipLabel>
    <relationshipName>Times</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <label>Épico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileEpic__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Escala Fibonacci 1,	2, 3,	5, 8,	13, 21, 34,55, 89, 144, 233, 377</inlineHelpText>
    <label># Pontos Estimados</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/DevPoints__c.field-meta.xml
<CustomField>
    <fullName>DevPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Dev</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nova</fullName>
                <default>true</default>
                <label>Nova</label>
            </value>
            <value>
                <fullName>Em Levantamento</fullName>
            </value>
            <value>
                <fullName>Aguardando Informações</fullName>
            </value>
            <value>
                <fullName>Em Escrita</fullName>
            </value>
            <value>
                <fullName>Revisão Arquiteto</fullName>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Sprint Backlog</fullName>
            </value>
            <value>
                <fullName>Em Andamento</fullName>
            </value>
            <value>
                <fullName>Aguardando APK/IPA</fullName>
            </value>
            <value>
                <fullName>Aguardando Deploy QA</fullName>
            </value>
            <value>
                <fullName>Em Teste Interno</fullName>
            </value>
            <value>
                <fullName>Liberado para PO</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Encerrada</fullName>
            </value>
            <value>
                <fullName>Aguardando APK%2FIPA</fullName>
                <isActive>false</isActive>
                <label>Aguardando APK%2FIPA</label>
            </value>
            <value>
                <fullName>Aguardando Deploy PROD</fullName>
                <isActive>false</isActive>
                <label>Aguardando Deploy PROD</label>
            </value>
            <value>
                <fullName>Em Validação Interna</fullName>
                <isActive>false</isActive>
                <label>Em Validação Interna</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AgileWorkControllerTest.cls
@isTest
public class AgileWorkControllerTest {
    @TestSetup
    public static void createData() {    

        Account acc = new Account();
        acc.Name = 'Cliente';
        // acc.CNPJ__c = '54.772.017/0018-34';
        insert acc;

        AgileProject__c project = new AgileProject__c();
        project.Account__c = acc.id;
        project.StartDate__c = Date.Today();
        project.FinalDate__c = Date.Today().addDays(30);
        project.GoLiveDate__c = Date.Today().addDays(29);
        project.InitialProjectValue__c = 123;
        project.Name = 'Implantação';
        insert project;
        
        AgileTeam__c team = new AgileTeam__c();
        team.AgileProject__c = project.id;
        team.Name = 'Time de Projeto';
        insert team;

        AgileSprint__c sprint = new AgileSprint__c();
        sprint.StartDate__c = Date.Today();
        sprint.FinalDate__c = Date.Today().addDays(30);
        sprint.Status__c = 'Em Execução';
        sprint.Name = 'Levantamento';
        sprint.Team__c = team.Id;
        insert sprint;
        
        AgileEpic__c epic = new AgileEpic__c();
        epic.Status__c = 'Não iniciado';
        epic.Name = 'Visão 360';
        epic.Team__c = team.Id;
        insert epic;

        AgileWork__c work = new AgileWork__c();
        work.Name = 'TEST';
        work.AgileEpic__c = epic.Id;
        work.BaPoints__c = 10;
        work.DevPoints__c = 11;
        work.RemainingBaPoints__c = 10;
        work.RemainingDevPoints__c = 11;
        work.Sprint__c = sprint.Id;
        work.Status__c = 'Nova';
        work.Team__c = team.id;
        insert work;
    }
    @isTest
    public static void summarizeWorks() {  
        AgileWork__c work = new AgileWork__c();
        work.Name = 'TEST';
        work.AgileEpic__c = [SELECT id FROM AgileEpic__c LIMIT 1].Id;
        work.BaPoints__c = 10;
        work.DevPoints__c = 11;
        work.RemainingBaPoints__c = 10;
        work.RemainingDevPoints__c = 11;
        work.Sprint__c = [SELECT id FROM AgileSprint__c LIMIT 1].Id;
        work.Status__c = 'Nova';
        work.Team__c = [SELECT id FROM AgileTeam__c LIMIT 1].id;
        insert work;  
    }
}