force-app/main/default/objects/AgileResource__c/AgileResource__c.object-meta.xml
<CustomObject>
    <label>Recurso</label>
    <nameField>
        <label>Nome de Recurso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileResource__c/fields/AgileUser__c.field-meta.xml
<CustomField>
    <fullName>AgileUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recursos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/WorkDays__c.field-meta.xml
<CustomField>
    <fullName>WorkDays__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Neste campo devemos adicionar a quantidade de horas produtivas por dia, esse campo será considerado para calculo de capacidade de cada consultor.</inlineHelpText>
    <label>Dias Trabalhados</label>
    <precision>13</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/WorkHours__c.field-meta.xml
<CustomField>
    <fullName>WorkHours__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>Neste campo devemos preencher com os dias uteis que teremos na Sprint</inlineHelpText>
    <label>Total de Horas Trabalhaveis</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileTeam__c/AgileTeam__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <label>Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeamMember__c/AgileTeamMember__c.object-meta.xml
<CustomObject>
    <label>Membro do Time</label>
    <nameField>
        <label>Nome de Membro do Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros do Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileResource__c.field-meta.xml
<CustomField>
    <fullName>AgileResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso</label>
    <referenceTo>AgileResource__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileTeam__c.field-meta.xml
<CustomField>
    <fullName>AgileTeam__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Alocação</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Função</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FunctionAgile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FunctionAgile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>InternalManager</fullName>
        <label>Gestor da Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalProjectManager</fullName>
        <label>Gerente de Projeto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalArchitect</fullName>
        <label>Arquiteto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalConsultant</fullName>
        <label>Consultor Funcional</label>
    </customValue>
    <customValue>
        <fullName>InternalDeveloper</fullName>
        <label>Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerManager</fullName>
        <label>Cliente: Gestor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProjectManager</fullName>
        <label>Cliente: Gerente de Projeto</label>
    </customValue>
    <customValue>
        <fullName>CustomerDeveloper</fullName>
        <label>Cliente: Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProductOwner</fullName>
        <label>Cliente: Product Owner</label>
    </customValue>
    <customValue>
        <fullName>CustomerIT</fullName>
        <label>Cliente: Usuário da TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerITLegacyTeam</fullName>
        <label>Cliente: Time Legado TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerKeyUser</fullName>
        <label>Cliente: Usuário Chave</label>
    </customValue>
    <masterLabel>Função Time Agile</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SprintBacklogTeamsController.cls
//public with sharing class NE_TeamsController {
public with sharing class SprintBacklogTeamsController {
    private SprintBacklogITeamDAO teamDAO = new SprintBacklogTeamDAO();

    public TeamResult getTeamList() {
        TeamResult response;
        try {
            response = new TeamResult();
            for(SObject teamData : teamDAO.getTeamList()) {
                AgileTeam__c team = teamDAO.castingObject(teamData);
                if(team.Sprints__r.size() > 0) {
                    response.data.add(new TeamData(team));
                }
            }
        } catch (Exception e) {
            response = new TeamResult(e);
        }
        return response;
    }

    public class TeamResult extends RemotingResult {
        public List<TeamData> data = new List<TeamData>();
        
        public TeamResult() {
            super();
        }

        public TeamResult(Exception e) {
            super(e);
        }
    }

    public class TeamData {
        public String id;
        public String name;
        public List<MemberData> memberList = new List<MemberData>();
        public List<SprintData> sprintList = new List<SprintData>();

        public TeamData() {}

        public TeamData(AgileTeam__c team) {
            this.id             = team.Id;
            this.name           = team.Name;
            for(AgileTeamMember__c member : team.Membros_do_Time__r) {
                this.memberList.add(new MemberData(member));
            }
            for(AgileSprint__c sprint : team.Sprints__r) {
                this.sprintList.add(new SprintData(sprint));
            }
        }
    }

    public class MemberData {
        public String id;
        public String name;
        public String photo;
        public Decimal allocation;
        public PicklistData role;
        public PicklistData type;

        public MemberData() {}

        public MemberData(AgileTeamMember__c member) {
            if(member != null) {
                this.id             = member.Id;
                this.name           = String.isNotBlank(member.Name) ? member.Name : member.AgileResource__r.AgileUser__r.Name;
                this.photo          = member.AgileResource__r.AgileUser__r.FullPhotoUrl;
                this.allocation     = member.Allocated__c;
                this.role           = new PicklistData(member.Role__c, (String) member.get('RoleLabel'));
                this.type           = new PicklistData('Internal', 'Internal');
            }
        }
    }

    public class SprintData {
        public String id;
        public String name;
        public String startDate;
        public String endDate;
        public Decimal totalWorkDays;
        public Decimal totalWorkHours;
        public String daysRemaining;

        public SprintData() {}

        public SprintData(AgileSprint__c sprint) {
            if(sprint != null) {
                this.id             = sprint.Id;
                this.name           = sprint.Name;
                this.startDate      = String.valueOf(sprint.StartDate__c);
                this.endDate        = String.valueOf(sprint.FinalDate__c);
                this.totalWorkDays  = sprint.WorkDays__c;
                this.totalWorkHours = sprint.WorkHours__c;
                this.daysRemaining  = ' - ';
            }  
        }
    }
}