force-app/main/default/objects/AgileResource__c/AgileResource__c.object-meta.xml
<CustomObject>
    <label>Recurso</label>
    <nameField>
        <label>Nome de Recurso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileResource__c/fields/AgileUser__c.field-meta.xml
<CustomField>
    <fullName>AgileUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Recursos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/FinalDate__c.field-meta.xml
<CustomField>
    <fullName>FinalDate__c</fullName>
    <label>Data Término</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/WorkDays__c.field-meta.xml
<CustomField>
    <fullName>WorkDays__c</fullName>
    <defaultValue>8</defaultValue>
    <inlineHelpText>Neste campo devemos adicionar a quantidade de horas produtivas por dia, esse campo será considerado para calculo de capacidade de cada consultor.</inlineHelpText>
    <label>Dias Trabalhados</label>
    <precision>13</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/WorkHours__c.field-meta.xml
<CustomField>
    <fullName>WorkHours__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>Neste campo devemos preencher com os dias uteis que teremos na Sprint</inlineHelpText>
    <label>Total de Horas Trabalhaveis</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileTeam__c/AgileTeam__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <label>Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeamMember__c/AgileTeamMember__c.object-meta.xml
<CustomObject>
    <label>Membro do Time</label>
    <nameField>
        <label>Nome de Membro do Time</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros do Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileResource__c.field-meta.xml
<CustomField>
    <fullName>AgileResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso</label>
    <referenceTo>AgileResource__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/AgileTeam__c.field-meta.xml
<CustomField>
    <fullName>AgileTeam__c</fullName>
    <label>Time</label>
    <referenceTo>AgileTeam__c</referenceTo>
    <relationshipLabel>Membros do Time</relationshipLabel>
    <relationshipName>Membros_do_Time</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Alocação</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AgileTeamMember__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Função</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FunctionAgile</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/FunctionAgile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>InternalManager</fullName>
        <label>Gestor da Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalProjectManager</fullName>
        <label>Gerente de Projeto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalArchitect</fullName>
        <label>Arquiteto Consultoria</label>
    </customValue>
    <customValue>
        <fullName>InternalConsultant</fullName>
        <label>Consultor Funcional</label>
    </customValue>
    <customValue>
        <fullName>InternalDeveloper</fullName>
        <label>Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerManager</fullName>
        <label>Cliente: Gestor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProjectManager</fullName>
        <label>Cliente: Gerente de Projeto</label>
    </customValue>
    <customValue>
        <fullName>CustomerDeveloper</fullName>
        <label>Cliente: Desenvolvedor</label>
    </customValue>
    <customValue>
        <fullName>CustomerProductOwner</fullName>
        <label>Cliente: Product Owner</label>
    </customValue>
    <customValue>
        <fullName>CustomerIT</fullName>
        <label>Cliente: Usuário da TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerITLegacyTeam</fullName>
        <label>Cliente: Time Legado TI</label>
    </customValue>
    <customValue>
        <fullName>CustomerKeyUser</fullName>
        <label>Cliente: Usuário Chave</label>
    </customValue>
    <masterLabel>Função Time Agile</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SprintBacklogTeamDAO.cls
//public with sharing class NE_TeamDAO implements ITeamDAO {
public with sharing class SprintBacklogTeamDAO implements SprintBacklogITeamDAO {
        public AgileTeam__c castingObject(SObject obj) {
            return (AgileTeam__c) obj;
        }
    
        public List<AgileTeam__c> getTeamList() {
            List<String> teamIdList = new List<String>();
            for(AgileTeamMember__c member : [
                SELECT  Id, Name,
                        AgileTeam__c
                  FROM  AgileTeamMember__c
                 WHERE  AgileResource__r.AgileUser__c = : UserInfo.getUserId()
            ]) {
                teamIdList.add(member.AgileTeam__c);
            }
            return [
                SELECT  Id, Name, //agf__External_Name__c,
                        (
                            SELECT  Id, Name
                                    , AgileResource__r.AgileUser__r.Name, Allocated__c, 
                                    Role__c, toLabel(Role__c) RoleLabel, AgileResource__r.AgileUser__r.FullPhotoUrl
                              FROM  Membros_do_Time__r
                          ORDER BY  Name
                        ),
                        (
                            SELECT  Id, Name, StartDate__c, FinalDate__c, 
                              WorkDays__c, WorkHours__c
                              FROM  Sprints__r
                          ORDER BY  StartDate__c
                        )
                  FROM  AgileTeam__c
                 WHERE  Id IN :teamIdList
              ORDER BY  Name
            ];
        }
    }