force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <label># Pontos BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/DevPoints__c.field-meta.xml
<CustomField>
    <fullName>DevPoints__c</fullName>
    <label># Pontos Dev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/AgileWork__c.object-meta.xml
<CustomObject>
    <label>Work</label>
    <nameField>
        <label>Work</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Works</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileWork__c/fields/BaPoints__c.field-meta.xml
<CustomField>
    <fullName>BaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Escala Fibonacci 1,	2, 3,	5, 8,	13, 21, 34,55, 89, 144, 233, 377</inlineHelpText>
    <label># Pontos Estimados</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/DevPoints__c.field-meta.xml
<CustomField>
    <fullName>DevPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Dev</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingBaPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingBaPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes BA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/RemainingDevPoints__c.field-meta.xml
<CustomField>
    <fullName>RemainingDevPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label># Pontos Restantes Dev</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AgileWork__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AgileSprint__c.Team__c</field>
            <operation>equals</operation>
            <valueField>$Source.Team__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Works</relationshipLabel>
    <relationshipName>Works</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AgileWorkController.cls
public class AgileWorkController {
    
    private static Boolean isEnabled;

    static{
        isEnabled = true;
    }

    public static Boolean isTriggerEnabled(){
        return isEnabled;
    }
    
    public static Boolean disableTrigger(){
        return isEnabled = false;
    }

    public static Boolean enableTrigger(){
        return isEnabled = true;
    }


    public static void summarizeWork(AgileWork__c[] context) {
        Map<Id, AgileSprint__c> sprintUpdateMap = new Map<Id, AgileSprint__c>();
        for(AgileWork__c record : context){
            System.debug('RecordID' + record.Sprint__c);
            if(record.Sprint__c != null)
                sprintUpdateMap.put(record.Sprint__c, new AgileSprint__c(Id = record.Sprint__c, RemainingBaPoints__c = 0, RemainingDevPoints__c = 0, BaPoints__c = 0, DevPoints__c = 0));
        }
		System.debug('sprintUpdateMap 2' + sprintUpdateMap);
        if(sprintUpdateMap.isEmpty()) return;

        for(AgileWork__c record : [SELECT id, Sprint__c, RemainingBaPoints__c, RemainingDevPoints__c, BaPoints__c, DevPoints__c FROM AgileWork__c WHERE Sprint__c IN :sprintUpdateMap.keySet()]){
            AgileSprint__c newRec = sprintUpdateMap.get(record.Sprint__c);
            newRec.RemainingBaPoints__c  += (record.RemainingBaPoints__c != null ? record.RemainingBaPoints__c : 0);
            newRec.RemainingDevPoints__c += (record.RemainingDevPoints__c != null ? record.RemainingDevPoints__c : 0);
            newRec.BaPoints__c           += (record.BaPoints__c != null ? record.BaPoints__c : 0);
            newRec.DevPoints__c          += (record.DevPoints__c != null ? record.DevPoints__c : 0);
            sprintUpdateMap.put(record.Sprint__c, newRec);
        }
		System.debug('sprintUpdateMap' + sprintUpdateMap);
        if(!sprintUpdateMap.isEmpty()){
            update sprintUpdateMap.values();
        }
    }
}